channels:
  - conda-forge
dependencies:
  - pip==20.1.1
  - python==3.7.5
  - pip:
      - dop-rpaframework==1.2.3
      - rpaframework==11.5.1
      - rpaframework-recognition==0.7.2
      - pdf2image==1.16.0